### ISSUE TITLE
Package installation failed

### ISSUE THREAD

**Issue by GuguGama** [ErasmusOIC/SMoLR#12]
Dear @JASlotman 

I tried installing the SMoLR package from GitHub as directed in the ReadMe file. Every other required package were installed successfully. However the last line of code `install_github("ErasmusOIC/SMoLR", build_vignettes = TRUE)` gives the error below

√  checking for file 'C:\Users\24647594\AppData\Local\Temp\RtmpKSTwyk\remotes56d03fc474e\ErasmusOIC-SMoLR-c61fe38/DESCRIPTION' (382ms)
-  preparing 'SMoLR':
√  checking DESCRIPTION meta-information ... 
-  installing the package to build vignettes
         -----------------------------------
-  installing *source* package 'SMoLR' ...
   ** using staged installation
   ** R
   ** data
   *** moving datasets to lazyload DB
   ** inst
   ** byte-compile and prepare package for lazy loading
   Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
     there is no package called 'manipulateWidget'
   Calls: <Anonymous> ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
   Execution halted
   ERROR: lazy loading failed for package 'SMoLR'
-  removing 'C:/Users/24647594/AppData/Local/Temp/RtmpQZCT3y/Rinst237c57a96a26/SMoLR'
         -----------------------------------
   ERROR: package installation failed
Error: Failed to install 'SMoLR' from GitHub:
  System command 'Rcmd.exe' failed, exit status: 1, stdout & stderr were printed
> 

Kindly help look into this. 

Thank you in anticipation!

**Comment by JASlotman** [comment]
Dear Gurugama,

I think this problem could be solved by installing the "manupulateWidget" package from CRAN, Ive seen this before I'll look if I can add this to the dependencies of the SMOLR package. Thank you for trying our package.

Kind regards,

Johan Slotman

**Comment by JASlotman** [comment]
I thrust that the installation worked, and consider this issue closed.
